const Styles = require('.');

describe("Styles", () => {
  const data = {
   "EXCEL_PRESET_FIRST": {
     "background-color": "FF000000",
     "background-style": "none",
     "border-bottom-color": null,
     "border-bottom-style": null,
     "border-left-color": null,
     "border-left-style": null,
     "border-right-color": null,
     "border-right-style": null,
     "border-top-color": null,
     "border-top-style": null,
     "color": "FF000000",
     "font-family": "Calibri",
     "font-size": 11,
   },
   "EXCEL_PRESET_SECOND": {
     "background-color": "FF000000",
     "background-style": "gray125",
     "border-bottom-color": null,
     "border-bottom-style": null,
     "border-left-color": null,
     "border-left-style": null,
     "border-right-color": null,
     "border-right-style": null,
     "border-top-color": null,
     "border-top-style": null,
     "color": "FF000000",
     "font-family": "Calibri",
     "font-size": 11,
    },
    "::defaults": {
      "display": "text",
      "font-family": "Calibri",
      "vertical-align": "center",
      "text-align": "center",
      "white-space": false,
      "font-size": 14,
      "color": "FF111111",
      "border-bottom-color": null,
      "border-bottom-style": null,
      "border-left-color": null,
      "border-left-style": null,
      "border-right-color": null,
      "border-right-style": null,
      "border-top-color": null,
      "border-top-style": null,
      "background-color": "FF000000",
      "background-style": "none",
    },
    "::row(1)": {
      "display": "text",
      "font-family": "Calibri",
      "vertical-align": "center",
      "text-align": "center",
      "white-space": false,
      "font-size": 14,
      "color": "FF111111",
      "border-top-color": null,
      "border-left-color": null,
      "border-right-color": null,
      "border-bottom-color": null,
      "border-top-style": null,
      "border-left-style": null,
      "border-right-style": null,
      "border-bottom-style": null,
      "background-color": "FF000000",
      "background-style": "none",
      "position": "fixed",
    },
    "STATE_100": {
      "display": "text",
      "font-family": "Calibri",
      "vertical-align": "center",
      "text-align": "center",
      "white-space": false,
      "font-size": 14,
      "color": "FF111111",
      "border-top-color": "FF111111",
      "border-left-color": "FF111111",
      "border-right-color": "FF111111",
      "border-bottom-color": "FF111111",
      "border-top-style": "thick",
      "border-left-style": "thick",
      "border-right-style": "thick",
      "border-bottom-style": "thick",
      "background-color": "FF8C72B2",
      "background-style": "solid",
    },
    "STATE_200": {
      "display": "text",
      "font-family": "Calibri",
      "vertical-align": "center",
      "text-align": "center",
      "white-space": false,
      "font-size": 14,
      "color": "FF111111",
      "border-top-color": "FF111111",
      "border-left-color": "FF111111",
      "border-right-color": "FF111111",
      "border-bottom-color": "FF111111",
      "border-top-style": "thick",
      "border-left-style": "thick",
      "border-right-style": "thick",
      "border-bottom-style": "thick",
      "background-color": "FF46A0DF",
      "background-style": "solid",
    },
    "STATE_300": {
      "display": "text",
      "font-family": "Calibri",
      "vertical-align": "center",
      "text-align": "center",
      "white-space": false,
      "font-size": 14,
      "color": "FF111111",
      "border-top-color": "FF111111",
      "border-left-color": "FF111111",
      "border-right-color": "FF111111",
      "border-bottom-color": "FF111111",
      "border-top-style": "thick",
      "border-left-style": "thick",
      "border-right-style": "thick",
      "border-bottom-style": "thick",
      "background-color": "FFDFAB46",
      "background-style": "solid",
    },
    "STATE_400": {
      "display": "text",
      "font-family": "Calibri",
      "vertical-align": "center",
      "text-align": "center",
      "white-space": false,
      "font-size": 14,
      "color": "FF111111",
      "border-top-color": "FF111111",
      "border-left-color": "FF111111",
      "border-right-color": "FF111111",
      "border-bottom-color": "FF111111",
      "border-top-style": "thick",
      "border-left-style": "thick",
      "border-right-style": "thick",
      "border-bottom-style": "thick",
      "background-color": "FFDF4654",
      "background-style": "solid",
    },
    "STATE_500": {
      "display": "text",
      "font-family": "Calibri",
      "vertical-align": "center",
      "text-align": "center",
      "white-space": false,
      "font-size": 14,
      "color": "FF111111",
      "border-top-color": "FF111111",
      "border-left-color": "FF111111",
      "border-right-color": "FF111111",
      "border-bottom-color": "FF111111",
      "border-top-style": "thick",
      "border-left-style": "thick",
      "border-right-style": "thick",
      "border-bottom-style": "thick",
      "background-color": "FF000000",
      "background-style": "none",
    },
    "STATE_ERROR": {
      "display": "text",
      "font-family": "Calibri",
      "vertical-align": "center",
      "text-align": "center",
      "white-space": false,
      "font-size": 14,
      "color": "FF111111",
      "border-top-color": "FF111111",
      "border-left-color": "FF111111",
      "border-right-color": "FF111111",
      "border-bottom-color": "FF111111",
      "border-top-style": "thick",
      "border-left-style": "thick",
      "border-right-style": "thick",
      "border-bottom-style": "thick",
      "background-color": "FFAC0000",
      "background-style": "solid",
    },
    "URL": {
      "display": "link",
      "font-family": "Calibri",
      "vertical-align": "center",
      "text-align": "left",
      "white-space": false,
      "font-size": 14,
      "color": "FF111111",
      "border-top-color": "FF111111",
      "border-left-color": "FF111111",
      "border-right-color": "FF111111",
      "border-bottom-color": "FF111111",
      "border-top-style": "thick",
      "border-left-style": "thick",
      "border-right-style": "thick",
      "border-bottom-style": "thick",
      "background-color": "FF000000",
      "background-style": "none",
    },
    "EMPTY": {
      "display": "text",
      "font-family": "Calibri",
      "vertical-align": "center",
      "text-align": "center",
      "white-space": false,
      "font-size": 14,
      "color": "FF111111",
      "border-top-color": null,
      "border-left-color": null,
      "border-right-color": null,
      "border-bottom-color": null,
      "border-top-style": null,
      "border-left-style": null,
      "border-right-style": null,
      "border-bottom-style": null,
      "background-color": "FF000000",
      "background-style": "none",
    }
  };

  test("addFile & collect", async () => {
    const styles = new Styles();

    styles.addFile(__dirname, './styles.test.css');

    await styles.ready();

    result = styles.collect();

    expect(result).toEqual(data);
  });

  test("init with file & collect", async () => {
    const styles = new Styles(__dirname, './styles.test.css');

    await styles.ready();

    result = styles.collect();

    expect(result).toEqual(data);
  });
});
