module.exports = {
  'background': require('./properties/background'),
  'background-color': require('./properties/background-color'),
  'background-style': require('./properties/background-style'),
  'border': require('./properties/border'),
  'border-bottom': require('./properties/border-bottom'),
  'border-bottom-color': require('./properties/border-bottom-color'),
  'border-bottom-style': require('./properties/border-bottom-style'),
  'border-left': require('./properties/border-left'),
  'border-left-color': require('./properties/border-left-color'),
  'border-left-style': require('./properties/border-left-style'),
  'border-right': require('./properties/border-right'),
  'border-right-color': require('./properties/border-right-color'),
  'border-right-style': require('./properties/border-right-style'),
  'border-top': require('./properties/border-top'),
  'border-top-color': require('./properties/border-top-color'),
  'border-top-style': require('./properties/border-top-style'),
  'color': require('./properties/color'),
  'display': require('./properties/display'),
  'font-family': require('./properties/font-family'),
  'font-size': require('./properties/font-size'),
  'height': require('./properties/height'),
  'position': require('./properties/position'),
  'text-align': require('./properties/text-align'),
  'vertical-align': require('./properties/vertical-align'),
  'width': require('./properties/width'),
};
